### ISSUE TITLE
Golang parser time format does not match actual iptables logging time format, causing error to scrape logs

### ISSUE THREAD

**Issue by antoooks** [box/kube-iptables-tailer#10]
After I created the Daemonset on the remote cluster, the `kube-iptables-tailer` were running but it throws this error
```
E0903 11:47:30.085747       1 parser.go:31] Error retrieving log time to check expiration: parsing time "Sep" as "2006-01-02T15:04:05.000000-07:00": cannot parse "Sep" as "2006"
```

Time format expected by `kube-iptables-tailer`
```
2019-02-04T10:10:12.345678-07:00 hostname EXAMPLE_LOG_PREFIX: SRC=SOURCE_IP DST=DESTINATION_IP ...
```

Actual iptables log time format:
```
Sep  3 11:38:30 ip-xx-xx-xx-xx kernel: [324352.855587] flannel-drop: ....
```

This is my environment spec:
```
Distributor ID:	Ubuntu
Description: Ubuntu 16.04.5 LTS
Release: 16.04
Codename: xenial
Cloud Provider: AWS on EC2 Instance
```
Kubernetes API version
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}

with kube-proxy installed
```

The time format seems mismatched, did you somehow customize your iptables logging time format? What is your iptables log time format?

**Comment by dilyar85** [comment]
Hi @antoooks!

Currently kube-iptables-tailer only supports logs of iptables using [rfc3339](https://tools.ietf.org/html/rfc3339) for the timestamp. 
As you pointed out, this is not great. So I am going to leave this issue open until we fix it by making the timestamp configurable.

Thanks again for reporting the issue to us.

**Comment by antoooks** [comment]
Great!! Thank you @dilyar85 

Also one little question, can you scrape more than 1 log prefix?

**Comment by antoooks** [comment]
bump
