### ISSUE TITLE
Install instructions are outdated

### ISSUE THREAD

**Issue by LSmyrnaios** [box/kube-iptables-tailer#15]
Hello, I tried to install `kube-iptables-tailer` followiong the instructions in README, but ran into the following problems:
 - The command `git clone github.com/box/kube-iptables-tailer` fails. The correct command is `git clone https://github.com/box/kube-iptables-tailer.git`
- The command `cd $GOPATH/src/github.com/box/kube-iptables-tailer` fails with "`No such file or directory`". The correct command is `cd kube-iptables-tailer`
- I do not know what "`CHAIN_NAME`" to use in the command `iptables -A CHAIN_NAME -j LOG --log-prefix "EXAMPLE_LOG_PREFIX: "`

**Comment by dilyar85** [comment]
`CHAIN_NAME`is just the selected chain where you want to append the rule-specification in that `iptables` command. You can find more details about chains in [this page](https://unix.stackexchange.com/questions/506729/what-is-a-chain-in-iptables#:~:text=Iptables%20chains%20are%20just%20lists,then%20be%20called%20from%20others.).
Created https://github.com/box/kube-iptables-tailer/pull/21 to address the first two issues above. Will ask one of my teammates to review and merge it on Monday.
