### ISSUE TITLE
Is there is a method or config to don't use k8s, only own servers?

### ISSUE THREAD

**Issue by muraveynovosibirsk** [box/kube-iptables-tailer#20]
From README.md:
> For IPs that do not match any Pods in your cluster, a DNS lookup will be performed to get subjects involved in the packet drops.

**Comment by dilyar85** [comment]
Hi @muraveynovosibirsk,

Unfortunately, there is no such config supported yet (feel free to submit a PR if you think it's nice to have and I can help review it). However, if the IPs from iptables logs are not found inside K8s clusters, the service will always perform a DNS lookup to try locating the related subjects.
