### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by endzyme** [box/kube-iptables-tailer#35]
Is this project still maintained? I see the last few people who have managed PRs here are no longer working at Box. Is this an actively maintained project?

**Comment by mtparet** [comment]
Good question, we are using this software and also maintain the helm chart https://artifacthub.io/packages/helm/lifen/kube-iptables-tailer

**Comment by mtparet** [comment]
We are maintaining this fork https://github.com/honestica/kube-iptables-tailer, happy to help !
