### ISSUE TITLE
Reading iptables entries from journald

### ISSUE THREAD

**Issue by eLco** [box/kube-iptables-tailer#4]
Hi,

is it possible to read iptables log entries from journald?

Thank you.

**Comment by dilyar85** [comment]
Hi @eLco 

I think it should be possible to read iptables logs from journald as long as it's stored somewhere in your host with the log entry containing source and destination IPs of dropped packets. You need to provide the path of your journald log to env var `IPTABLES_LOG_PATH` and log prefix defined in your iptables chains to`IPTABLES_LOG_PREFIX`.

**Comment by TheKangaroo** [comment]
would love to see ~~this implemented~~ #5 merged 😇

**Comment by dilyar85** [comment]
Closing this issue as the corresponding PR #5 was merged.
